title: Ballard Chiropractic
email: 
description: ""
baseurl: "chiro/"
url: ""
# uncomment these lines to minify your css
# sass:
#     style: compressed
exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
  - .gitignore
