title: Ballard Chiropractic
email: 
description: ""
baseurl: ""
url: "Chiro"
# uncomment these lines to minify your css
# sass:
#     style: compressed
exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
  - .gitignore
